# Version of Docker-compose
version: '3.8'
services:
  react-node-tutorial:
   build: .
   container_name: node_container
   ports: 
    - 5000:5000
   volumes:
      # Syntax <nameOfVolume>:<directorInDocker>
      - .:/app
  client:
   build: ./client
   container_name: react_container
   ports: 
    - 3000:3000
   volumes:
     - ./client:/app
   stdin_open: true
   tty: true
   
   
      
